/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizzer;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author pasca
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
       // this.setUndecorated(true);
       // this.setAlwaysOnTop(true);
        this.setResizable(true);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = 1280;
        int ysize = 1024;
        this.setSize(xsize, ysize);
        mySettings();
        
       
    }
    
    private boolean jaja = true;
    private boolean jaja1 = true;
     private boolean ant = false;
     private int rAnt = 0;
     private int text = 0;
    private ImageIcon pic2;
    private ImageIcon pic1;
    private String pass1;
    private String pass2;
    private String pass3;
     private String ben1;
    

    public void pandern(){
        pass1 = String.valueOf(jPasswordField4.getPassword());
        pass2 = String.valueOf(jPasswordField5.getPassword());
        pass3 = String.valueOf(jPasswordField6.getPassword());
        /*
           if(!pass1.equals(pass)){
        jPasswordField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, Color.red));
        jPasswordField4.setText(null);
        } else { 
        if(!pass2.equals(pass3)){
        jPasswordField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, Color.red));
        jPasswordField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, Color.red));
        jPasswordField5.setText(null);
        jPasswordField6.setText(null);
        } else {
        pass = pass2;
        }
        }
        */
            
    }
    
    public void bander(){
       /* ben1 = jTextField1.getText(){
        if(ben1.equals(ben){
        jTextfield1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, Color.red));
        } else {
        
        ben = ben1;
        }
        }
  
        */
    }
    
    
 
    public void mySettings(){
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jPanel1.setOpaque(false);
        jPanel5.setVisible(true);
        jPanel4.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
       jPanel13.setVisible(false);
        jPanel5.setVisible(false);
        jPanel10.setVisible(false);
        
        jLabel13.setVisible(false);
        jPanel15.setVisible(false);
       jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.gray));
       jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.gray));
       
        jPanel8.setVisible(true);
        //jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPasswordField6 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 1024));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 59, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(59, 59, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Er duscht sich nicht sehr oft");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 520, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kevin ist schuld.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 730, 520, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Es ist angeboren");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 520, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Er möchte so riechen wie Berta");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, 520, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Q1)");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 70, 70));

        jLabel2.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Warum stinkt Jan so hart nach Müll?");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 860, 70));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Frage:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 60, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("1/245");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -3, 70, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ATXRQVe4.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 440, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/frage0661.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 550, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/frage0661.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 550, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/frage0661.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 550, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/frage0661.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 710, 550, 80));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/frage5001.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 950, 85));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 830));

        jLabel17.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nächste Frage");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 910, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/idk4.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 890, 300, 80));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1004));

        jPanel4.setBackground(new java.awt.Color(59, 59, 61));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel6.setText("Bearbeitete Fragen:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 360, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Fragen richtig beantwortet :");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("0/215");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 375, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel24.setText("0/215");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 964));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1004));

        jPanel8.setBackground(new java.awt.Color(59, 59, 61));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Einstellungen");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 515, -1, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Statistik");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 355, -1, -1));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Spielen");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 195, -1, -1));

        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/idk1.png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel29MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel29MousePressed(evt);
            }
        });
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 340, 80));

        jLabel30.setForeground(new java.awt.Color(102, 204, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/idk1.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel30MousePressed(evt);
            }
        });
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 380, 80));

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/idk1.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel31MousePressed(evt);
            }
        });
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 370, 80));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 964));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1004));

        jPanel9.setBackground(new java.awt.Color(59, 59, 61));
        jPanel9.setMinimumSize(new java.awt.Dimension(1280, 1004));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setToolTipText("dad");
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel25.setText("-> Benutzernamen ändern");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel26.setText("-> Passwort ändern");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel26MousePressed(evt);
            }
        });
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));
        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 964));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1004));

        jPanel13.setBackground(new java.awt.Color(59, 59, 61));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel27.setText("neue Benutzername:");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 420, -1));

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel11.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 240, -1));

        jPanel13.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 964));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        jPanel14.setBackground(new java.awt.Color(59, 59, 61));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel33.setText("alte Passwort:");
        jPanel15.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 180, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel34.setText("neue Passwort:");
        jPanel15.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel35.setText("Passwort wiederholen:");
        jPanel15.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jPasswordField4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPasswordField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField4KeyPressed(evt);
            }
        });
        jPanel15.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 310, -1));

        jPasswordField5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPasswordField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField5KeyPressed(evt);
            }
        });
        jPanel15.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 310, -1));

        jPasswordField6.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jPasswordField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField6KeyPressed(evt);
            }
        });
        jPanel15.add(jPasswordField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 310, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 964));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
       
    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
       if(ant == false ){
        if(jaja == true){
        ImageIcon f1 = new ImageIcon(getClass().getResource("/image/frage066.png"));
       jLabel10.setIcon(f1);
       }
       }
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        if(ant == false ){
          if(jaja == true){
        ImageIcon f2 = new ImageIcon(getClass().getResource("/image/frage0661.png"));
       jLabel10.setIcon(f2);
       }
       }
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        if(ant == false ){
        ImageIcon f1 = new ImageIcon(getClass().getResource("/image/frage066.png"));
       jLabel8.setIcon(f1);
    }
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        if(ant == false ){
        ImageIcon f2 = new ImageIcon(getClass().getResource("/image/frage0661.png"));
       jLabel8.setIcon(f2);
    }
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
       if(ant == false ){
        if(jaja == true){
        ImageIcon f2 = new ImageIcon(getClass().getResource("/image/frage066.png"));
       jLabel9.setIcon(f2);
        }
        }
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
       if(ant == false ){
        ImageIcon f2 = new ImageIcon(getClass().getResource("/image/frage0661.png"));
       jLabel9.setIcon(f2);
    }
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        if(ant == false ){
        ImageIcon f2 = new ImageIcon(getClass().getResource("/image/frage066.png"));
       jLabel11.setIcon(f2);
        }
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        if(ant == false ){
        if(jaja1 == true){
        ImageIcon f3 = new ImageIcon(getClass().getResource("/image/frage0661.png"));
       jLabel11.setIcon(f3);
        }
        }
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        ImageIcon n2 = new ImageIcon(getClass().getResource("/image/idk3.png"));
        jLabel16.setIcon(n2);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
       ImageIcon n3 = new ImageIcon(getClass().getResource("/image/idk4.png"));
       jLabel16.setIcon(n3);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        if(ant == false){
         if( rAnt == 2){
            ImageIcon f71237 = new ImageIcon(getClass().getResource("/image/richtig9.png"));
             jLabel8.setIcon(f71237);
        } else { 
            ImageIcon h3 = new ImageIcon(getClass().getResource("/image/falsch9.png"));
            jLabel8.setIcon(h3);
        }
        
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jaja = false;
        ant = true;
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
       jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jaja = true;
        ImageIcon f7 = new ImageIcon(getClass().getResource("/image/frage0661.png"));
       jLabel10.setIcon(f7);
       jLabel8.setIcon(f7);
       jLabel9.setIcon(f7);
       jLabel11.setIcon(f7);
       ant = false;
       //übergangslösung zum testen :)
       rAnt =   (int)((Math.random()) * 4 + 1);
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
         if(ant == false){
        if( rAnt == 4){
            ImageIcon f7127 = new ImageIcon(getClass().getResource("/image/richtig9.png"));
             jLabel11.setIcon(f7127);
        } else { 
            ImageIcon f121 = new ImageIcon(getClass().getResource("/image/falsch9.png"));
            jLabel11.setIcon(f121);
        }
        
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jaja = false;
        ant = true;
    }
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
           if(ant == false){
           if( rAnt == 3){
             ImageIcon f777 = new ImageIcon(getClass().getResource("/image/richtig9.png"));
             jLabel9.setIcon(f777);
        } else { 
            ImageIcon f17 = new ImageIcon(getClass().getResource("/image/falsch9.png"));
            jLabel9.setIcon(f17);
            
        }
        
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jaja = false;
        ant = true;
    }
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
          if(ant == false){
           if( rAnt == 1){
            ImageIcon f77 = new ImageIcon(getClass().getResource("/image/richtig9.png"));
             jLabel10.setIcon(f77);
        } else { 
            ImageIcon f1 = new ImageIcon(getClass().getResource("/image/falsch9.png"));
            jLabel10.setIcon(f1);
        }
        
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jaja = false;
        ant = true;
    }
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        jLabel13.setVisible(false);
        
        jPanel5.setVisible(false);
        jPanel13.setVisible(false);
        jPanel15.setVisible(false);
        
        jPanel8.setVisible(true);
        jPanel1.setVisible(false);
        jPanel4.setVisible(false);
        
       
        
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        ImageIcon st = new ImageIcon(getClass().getResource("/image/back1.png"));
             jLabel13.setIcon(st);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        ImageIcon st2 = new ImageIcon(getClass().getResource("/image/back.png"));
             jLabel13.setIcon(st2);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MousePressed
          jPanel8.setVisible(false);
          jPanel5.setVisible(true);
          jLabel13.setVisible(true);
          jPanel1.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel29MousePressed

    private void jLabel30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MousePressed
        jLabel13.setVisible(true);
        jPanel8.setVisible(false);
        jPanel1.setVisible(true);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jLabel30MousePressed

    private void jLabel31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MousePressed
       jLabel13.setVisible(true);
       jPanel8.setVisible(false);
       jPanel1.setVisible(true);
       jPanel10.setVisible(true);
       jPanel9.setVisible(true);
    }//GEN-LAST:event_jLabel31MousePressed

    private void jLabel29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseEntered
        ImageIcon pic2 = new ImageIcon(getClass().getResource("/image/idk.png")); 
        jLabel29.setIcon(pic2);
    }//GEN-LAST:event_jLabel29MouseEntered

    private void jLabel29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseExited
        ImageIcon pic1 = new ImageIcon(getClass().getResource("/image/idk1.png"));
        jLabel29.setIcon(pic1);
    }//GEN-LAST:event_jLabel29MouseExited

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
       ImageIcon pic2 = new ImageIcon(getClass().getResource("/image/idk.png"));
        jLabel30.setIcon(pic2);
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        ImageIcon pic1 = new ImageIcon(getClass().getResource("/image/idk1.png"));
        jLabel30.setIcon(pic1);
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        ImageIcon pic2 = new ImageIcon(getClass().getResource("/image/idk.png"));
        jLabel31.setIcon(pic2);
        
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        ImageIcon pic1 = new ImageIcon(getClass().getResource("/image/idk1.png"));
        jLabel31.setIcon(pic1);
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        jPanel10.setVisible(false);
        jPanel9.setVisible(false);
        jPanel13.setVisible(true);
    }//GEN-LAST:event_jLabel25MousePressed

    private void jLabel26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MousePressed
       jPanel10.setVisible(false);
        jPanel9.setVisible(false);
        jPanel15.setVisible(true);
    }//GEN-LAST:event_jLabel26MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //benutzername
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField4KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jPasswordField5.requestFocusInWindow();
        }
    }//GEN-LAST:event_jPasswordField4KeyPressed

    private void jPasswordField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField5KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jPasswordField6.requestFocusInWindow();
        }
    }//GEN-LAST:event_jPasswordField5KeyPressed

    private void jPasswordField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField6KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            pandern();
        }
    }//GEN-LAST:event_jPasswordField6KeyPressed

 
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

